describe('Shop actions', () => {
  it('Non auth user tries to purchase Random Pokemon', () => {
    cy.visit('/shop')
    cy.get('button').contains('$250 (Random Pokemon)').click()
    cy.get('.p-toast-message-error').contains('Error')
  })
  it('Non auth user tries to purchase selected pokemons', () => {
    cy.visit('/shop')
    cy.get('.card').find('button').find('span.pi-shopping-cart').first().click()
    cy.visit('/cart')
    cy.get('button').contains('Purchase').click()
    cy.get('.p-toast-message-error').contains('Error')
  })
  it('Auth user tries to purchase random pokemon', () => {
    cy.testRegister('test', 'test@test.com', '12345678', '12345678')
    cy.url({ timeout: 10000 }).should('eq', Cypress.config().baseUrl)
    cy.visit('/shop')
    cy.viewport(1280, 720)
    cy.contains('div', 'My bag: $1000', { timeout: 10000 }).should('be.visible')
    cy.get('button').contains('$250 (Random Pokemon)').click()
    cy.contains('div', /^My bag: \$?(750|800)$/, { timeout: 10000 }).should('be.visible')
    cy.task('deleteTestUser', { email: 'test@test.com' })
  })
  it('Auth user tries to purchase selected pokemon', () => {
    cy.testRegister('test', 'test@test.com', '12345678', '12345678')
    cy.url({ timeout: 10000 }).should('eq', Cypress.config().baseUrl)
    cy.visit('/shop')
    cy.viewport(1280, 720)
    cy.contains('div', 'My bag: $1000', { timeout: 10000 }).should('be.visible')
    cy.get('.card').find('button').find('span.pi-shopping-cart').first().click()
    cy.visit('/cart')
    cy.contains('div', 'My bag: $1000', { timeout: 10000 }).should('be.visible')
    cy.get('button').contains('Purchase').click()
    cy.contains('div', /^My bag: \$?(750)$/, { timeout: 10000 }).should('be.visible')
    cy.task('deleteTestUser', { email: 'test@test.com' })
  })
})
